### ISSUE TITLE
/listship does not work properly in MP because of the chunk loading

### ISSUE THREAD

**Issue by Spcemarine** [midspace/Space-Engineers-Admin-script-mod#120]
It seems like the chunk loading thing causes a bug where /listships only displays ships that are loaded by the client. I havent tested it yet but it'd make sense so we might have to fix this somehow.

**Comment by midspace** [comment]
It will need to run from the server to access all ships.
Otherwise, the Client only sees the few that are loaded into its memory.

**Comment by Spcemarine** [comment]
That's pretty inconvenient because we'll have to run anything connected to those lists on the server... Any ideas how to make `/save l` work again? Sending the whole map might take a while in certain cases.

**Comment by midspace** [comment]
Most of the commands are affected by the changes.

Even teleport. When specifying a name, it will have to consult the server to find that named item.  And then, use the server to find if the area is clear. :sob:

`/save l` is probably the only command we cannot make work as it used to.
We are reliant upon the game API for that.
Unless we do something absurd like teleport the player to every active location in the world, to force a download of all active assets, and the use `/save l`

**Comment by jpcsupplies** [comment]
Listship does work on a locally hosted map - which is likely as it is server side technically. So making it work server side to construct a string/array of all the ships, then pass that string to client admins looks like it should work.  

Going totally left field here -
Ever considered an alternate listship behavior to make it work like your scanore command?  (ie build a list of GPS points)   scan ore was able to bash out thousands of gps points in a matter of seconds, most servers only have at most 200 structures, 150 of which are usually individual blocks drifting to nowhere land..  Downside is drifting; you could stopall too I suppose.. But for admins doing cleanup work, gps's can be used with /j  to get to and they can manually remove gps as they delete the junk..
(Admittedly this appeals as such behavior could also be subverted for giving players "investigate location X" missions on my server !   )

(Btw: local save (save l) is still useful as a way to locally backup your own base/ships/roids   so it still has merit.  It is almost safe enough for players to use now, since you can only backup things you already found..)

**Comment by Spcemarine** [comment]
Well, it makes more sense to store the hotlists playerwise on the server and  to send the  dialog with the information to the player. We'll make it work again like before, no worries. ;)

**Comment by midspace** [comment]
The new features will change the way this works.
We'll need to review and relook at how to approach this.

http://forums.keenswh.com/threads/update-01-107-space-master-mode-building-from-cockpit-bugfixes.7372251/

**Comment by Spcemarine** [comment]
That was unexpected. Unfortunately, I'm not able to try that out at the moment.

**Comment by jpcsupplies** [comment]
alt-f10 seems to incorporate locating items by speed size or distance, allows you to cycle between ships of chosen category, stop them or remove them etc pretty much everything i did with listship tps stopall and deleteship at a mouse click away

**Comment by DigTron** [comment]
Space master has an option to simulate locally(pulls the whole world save I think and then tries to run like old multilayer), using it is not recommended but while the game may become unplayable to the admin, your command may work again under those conditions.

Have not tested but will when I get the chance.

**Comment by midspace** [comment]
I tried the pull list night, and it does what is intended.
I had a ship to find which wasn't in my local content.
Pulling down all the game world, found the ship 120Km away.

There was one seriously bad bug however.
Any active Projections turn into real ships. This only occurs on your Client side, and not on the server or anyone else connected.
If the projected ship is still under construction, you will end up with 2 ships overlapping, which causes serious sim speed loss (depending on how big the ship is).
I'm also sure (though I have tested), if you tried to interact with the projected ship controls, you would probably CTD.

**Comment by jpcsupplies** [comment]
projection bug happens regardless of run local, i had the same issue, zan or karni i think encountered it first and logged it to the keen steam bug forum

**Comment by midspace** [comment]
@Spcemarine if you can review and test what I've checked in. I think this will fix this issue, so we can close this.

**Comment by Spcemarine** [comment]
Looks good and worked for me.
