### ISSUE TITLE
Permission: Loading permission... Please try again later.

### ISSUE THREAD

**Issue by marky555** [midspace/Space-Engineers-Admin-script-mod#190]
Hello,
I am having the "Permission: Loading permission... Please try again later." message popping up in-game.
- impossible to chat on faction chat
- impossible to place blocks

I have found that this mod is installed on the server I am using.
I have found that this might be the mod causing this with this thread about an old issue:

https://github.com/midspace/Space-Engineers-Admin-script-mod/issues/71

Also this happened just after i updated Space engineers to the newer version.

If you need extra information from me, don't hesitate to contact me.

**Comment by marky555** [comment]
Problem fixed itself when the server has restarted.
I have been told that server updates the mods with restart.

**Comment by midspace** [comment]
It was major set of changes I published in the mod 12 hours ago.
Unfortunately these type of changes require the server to restart.

I try to time my update with the Space Engineers update, so that servers pick up the game and the mod changes together.

It's a dilemma for me, as I'm typically asleep when the Space Engineers update is released, and I have to either publish before them with the risk of the game breaking the mod anyhow, or after them and forcing server admins to restart a second time.

I was also slack in posting the necessary bit of information for 2 hours about the necessary restart.
My apologies for my slowness. I'll try to make sure information is posted more promptly in the future.
