### ISSUE TITLE
Documentation wiki pages

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#67]
Question, keep the documentation 'discussion' going in the Steam workshop for a list of all commands and examples, or move it to here on the Wiki pages.

Originally I put them into the Workshop description, until it grew too big for it. There is a character limit on how much you can put into the Workshop description.
So I started putting them into the Workshop 'discussion' as a pinned topic, as it made sense in my mind a the time that they should be kept together. Documentation and examples were in the same area as subscribing to the workshop mod. This would also allow for collaborators to also update any discussion posts (I think, as I only tested this with another mod briefly before breaking the mod because I was trying to have the collaborator account update it).

The pros of moving it to the Wiki pages here, means other users can also update the Wiki pages. There is also far more support for content, like images and formatting.
The cons, would be forcing any users to click on an external link from Steam to get to here to find information.
Unknowns. I don't think GitHub has built in support for localization, but we could add new pages in those languages much easier then on Steam. Also, as far as I know there is no search feature, so we will need to arrange the information in pages that are easier to navigate then how I have placed them currently.

Workshop 'discussion' thread link:
http://steamcommunity.com/workshop/filedetails/discussion/316190120/627456486404752973/

Wiki link:
https://github.com/midspace/Space-Engineers-Admin-script-mod/wiki

**Comment by Spcemarine** [comment]
I think using the wiki might be better because we have more options to structure the information which can lead to a better overview over the commands. Additionally I can finally edit it. Regarding the requirement for everyone to get to an external site, I am sure that as long as the site has a good structure and you find anything quickly there is no reason for the people to leave the site. I, myself, find the docs a bit confusing because it's a very very long list of many commands. Honestly, when I see mods in the workshop that have some instructions, I'm always happy if they rely on other options than steam because everything above a certain amount of information becomes kind of messy on steam.

Regarding localization, I wouldn't put this here on github. I think that might just turn out messy.
The search feature for the wiki might be missing, but we can add custom side bars to help the people navigate.

**Comment by zrisher** [comment]
Just to add my experience here, I've found that people coming from steam don't usually mind navigating to Github, but they are unlikely to create a Github account to add to commentary. So as long as you keep your primary methods of receiving user feedback within steam, having info hosted on Github isn't an issue.

That said, it seems to me like the best place to have documentation on how to use the commands would be in game. : ) Why not have a `/midspace help` command that opens up a notification window with general details and a listing of all commands, then display a notification window with usage info when a command is entered with insufficient arguments?

**Comment by midspace** [comment]
We already have several levels of help.

/help - lists of all commands.
/help <command> - full description of the command.
/? <command> - brief description of the command.
and, the brief description is provided when insufficient arguments are entered.

At the moment I'm also considering further work to how the /help command displays the list.
That is separate to the intent of this discussion however.

**Comment by zrisher** [comment]
Whoops, didn't realize that, sorry!

**Comment by midspace** [comment]
Documentation and links have been moved to git now.
I've made adjustments in the private messaging pages for the &lt;&gt; characters, but all other pages I've replaced them with {}.

A reminder (to myself also) that we have to be very careful with &lt;&gt; characters and use the escaped &amp;lt;&amp;gt; characters, otherwise parts of wiki documention will be missing and not make sense.
