### ISSUE TITLE
test /destructable setting on servers

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#83]
Retest /destructable to see if it's broken on single player since grinding prevention has been added.

Test to see if it works on servers.

**Comment by Spcemarine** [comment]
It works in SP and on listen and dedicated Server in MP, but still you are able to destroy blocks by grinding them.

**Comment by midspace** [comment]
I went back through Keen's posts, and it was only mentioned in the video and not the update text.
Grinding is only prevented in Scenario Edit mode when the cube is marked as not destructable.

**Comment by Spcemarine** [comment]
Shall we prevent any destruction now? Or with an optional setting? Or just leave it the way keen implemented it?

It would be quite easy to prevent it but a lot of work if we implement is as an option.

**Comment by midspace** [comment]
I think we should do it and it should be optional. Perhaps under /config.
We can reopen #69.

**Comment by Spcemarine** [comment]
Right, I didn't think of setting it for the whole world, I only thought of configuring it for each ship. It would be quite easy to store it in the cfg.

**Comment by midspace** [comment]
I was thinking, a world setting to make it optional, but it would only apply to ships that have Destructible=false.
` /config NoGrindIndestructible on `

Then later, we can add in the antigrief/safe zone.

I haven't looked at the Damage event handlers myself as yet, I'm guessing it's in IMyDamageSystem?
My only concern is, can we still get components from grinding blocks, even though the damage is ignored?

I'm guessing we may have the option of reflecting damage (which may cause a recursive loop if we aren't careful), or using a Physics push to force the questionable entity back.

**Comment by Spcemarine** [comment]
You can't get components because you'd have to grind it down to a level where you get your first component which is impossible. I'm far more concerned about syncing issues because I haven't tested it in MP yet.
Regarding reflecting damage isn't possible in each case as we only get the entity id of the attacker. If a player is grinding you get the grinder if you search for an entity with the attacker id and since we don't have access to those hand tools we can't find out who is grinding. I'd rather just cancel the damage for now.
